version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/acme.json:/acme.json
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/config:/etc/traefik/config
    networks:
      - proxy

  phase4:
    build:
      context: .
    container_name: phase4
    restart: unless-stopped
    volumes:
      - ./ap-config:/config
      - ./ap-generated:/generated
    labels:
      - "traefik.enable=true"
      # HTTP
      - "traefik.http.routers.phase4-http.rule=Host(`ap.net.recommand.com`)"
      - "traefik.http.routers.phase4-http.entrypoints=web"
      # HTTPS
      - "traefik.http.routers.phase4.rule=Host(`ap.net.recommand.com`)"
      - "traefik.http.routers.phase4.entrypoints=websecure"
      - "traefik.http.routers.phase4.tls.certresolver=letsencrypt"
      - "traefik.http.services.phase4.loadbalancer.server.port=8080"
    networks:
      - proxy

  phoss-smp:
    container_name: phoss-smp
    image: phelger/phoss-smp-xml:7.2.0
    restart: unless-stopped
    volumes:
      - ./smp-config:/config
      - ./smp-persistent:/var/smp/conf
    environment:
      - CATALINA_OPTS=-Dconfig.file=/config/application.properties
    labels:
      - "traefik.enable=true"
      # HTTP
      - "traefik.http.routers.phoss-smp-http.rule=Host(`smp.net.recommand.com`)"
      - "traefik.http.routers.phoss-smp-http.entrypoints=web"
      # HTTPS
      - "traefik.http.routers.phoss-smp.rule=Host(`smp.net.recommand.com`)"
      - "traefik.http.routers.phoss-smp.entrypoints=websecure"
      - "traefik.http.routers.phoss-smp.tls.certresolver=letsencrypt"
      - "traefik.http.services.phoss-smp.loadbalancer.server.port=8080"
    networks:
      - proxy

networks:
  proxy:
    name: proxy
    driver: bridge 