api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: proxy

certificatesResolvers:
  letsencrypt:
    acme:
      email: hello@brbx.ai
      storage: acme.json
      httpChallenge:
        entryPoint: web 